# Generated by Django 5.2 on 2025-04-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_profile_profile_picture_group_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='join_pin',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
